trigger:
- master

pool: 
  name: 'Anjal'

variables:
  solution: 'Cafe.sln'
  buildConfiguration: 'Release'
  publishPath: '$(build.artifactStagingDirectory)\WebApp'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetAuthenticate@0
  displayName: 'Authenticate NuGet'

- script: dotnet restore $(solution)
  displayName: 'Restore NuGet Packages'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build Solution'

- script: dotnet publish --configuration $(buildConfiguration) --output $(publishPath)
  displayName: 'Publish Solution'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(publishPath)'
    ArtifactName: 'PublishFiles'
    publishLocation: 'Container'
